<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Topnavaccordion",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Topnavaccordion extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Top Nav Accordion';
    }

    static function className()
    {
        return 'autogenerated-bce-topnavaccordion';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return ['content' => ['eyebrow' => ['text' => 'Lorem ipsum dolor'], 'heading' => ['text' => 'Lorem ipsum dolor sit amet'], 'subhead' => ['text' => 'Lorem ipsum dolor sit amet consectetur adipiscing elit'], 'content' => ['text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.'], 'buttons' => ['primary_button' => ['text' => 'Contact sales', 'link' => '#'], 'secondary_button' => ['text' => 'Learn more', 'link' => '#']]]];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "navigator",
        "Navigator",
        [c(
        "tabs",
        "Tabs",
        [c(
        "tab_title",
        "Tab Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "accordion",
        "Accordion",
        [c(
        "content_icon",
        "Content Icon",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content_image",
        "Content Image",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content_title",
        "Content Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Tab', 'buttonName' => 'Add Tab']],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['inlineScripts' => [';(function(){
  const config = {
    slidesPerView: 1,
    spaceBetween: 20,
    observer: true,
    observeParents: true,
    observeSlideChildren: true,
    navigation: {
      nextEl: \'.slider-navigation .swiper-button-next-%%UNIQUESLUG%%\',
      prevEl: \'.slider-navigation .swiper-button-prev-%%UNIQUESLUG%%\'
    },
    pagination: {
      el: \'.slider-navigation .swiper-pagination-%%UNIQUESLUG%%\',
      clickable: true,
      type: \'bullets\'
    }
  };

  function initColumnsSlider() {
    document
      .querySelectorAll(\'.swiper-%%UNIQUESLUG%%\')
      .forEach(el => {
        if (!el.swiper) {
          new Swiper(el, config);
        } else {
          el.swiper.update();
        }
      });
  }

  initColumnsSlider();

  window.addEventListener(\'resize\', initColumnsSlider);

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on(\'builder:loaded builder:rendered\', initColumnsSlider);
  }
})();
',';(function () {
  const module = document.querySelector(\'.autogenerated-bce-topnavaccordion\');

  function isMobile() {
    return window.matchMedia(\'(max-width: 1023px)\').matches;
  }

  function initMobileTabs() {
    const trigger = module.querySelector(".bde-mobile-tab-trigger");
    const dropdown = module.querySelector(".bde-mobile-dropdown-options");
    const tabContents = module.querySelectorAll(".bde-mobile-tab-content");

    if (!trigger || !dropdown || tabContents.length === 0) return;

    // Extract tab titles from data attributes
    const tabTitles = Array.from(tabContents).map(tab => tab.dataset.tabTitle);

    let activeIndex = 0; // Start with first tab

    // Toggle dropdown visibility
    trigger.addEventListener("click", function () {
      const expanded = this.getAttribute("aria-expanded") === "true";
      this.setAttribute("aria-expanded", !expanded);
      dropdown.style.display = expanded ? "none" : "block";
    });

    // Function to update the dropdown list excluding the currently selected tab
    function rebuildDropdown(active) {
      dropdown.innerHTML = ""; // Clear existing options

      tabTitles.forEach((title, i) => {
        if (i !== active) {
          const li = document.createElement("li");
          li.setAttribute("data-tab-index", i);
          li.textContent = title;
          dropdown.appendChild(li);

          li.addEventListener("click", function () {
            activeIndex = i;

            // Update label
            trigger.querySelector(".bde-accordion-title").innerText = this.innerText;
            trigger.setAttribute("aria-expanded", "false");
            dropdown.style.display = "none";

            // Show correct tab content
            tabContents.forEach((tab, j) => {
              tab.style.display = j == activeIndex ? "block" : "none";
            });

            // Init Swiper if not yet initialized
            const swiperEl = module.querySelector(`.swiper-${activeIndex}`);
            if (!swiperEl.classList.contains("swiper-initialized")) {
              new Swiper(`.swiper-${activeIndex}`, {
                slidesPerView: 1,
                spaceBetween: 24,
                pagination: {
                  el: `.swiper-pagination-${activeIndex}`,
                  clickable: true
                },
                navigation: {
                  nextEl: `.swiper-button-next-${activeIndex}`,
                  prevEl: `.swiper-button-prev-${activeIndex}`
                }
              });
            }

            // Rebuild dropdown to reflect new active tab
            rebuildDropdown(activeIndex);
          });
        }
      });
    }

    // Init first Swiper and dropdown
    const firstSwiper = module.querySelector(`.swiper-0`);
    if (firstSwiper && !firstSwiper.classList.contains("swiper-initialized")) {
      new Swiper(`.swiper-0`, {
        slidesPerView: 1,
        spaceBetween: 24,
        pagination: {
          el: `.swiper-pagination-0`,
          clickable: true
        },
        navigation: {
          nextEl: `.swiper-button-next-0`,
          prevEl: `.swiper-button-prev-0`
        }
      });
    }

    rebuildDropdown(activeIndex); // Setup dropdown for initial state
  }

  // ---- DESKTOP LOGIC ---- //

  function initDesktopTabs(tabButtons, tabPanels) {
    tabButtons.forEach((btn, i) => {
      btn.addEventListener(\'click\', function() {
        tabButtons.forEach((b, j) => {
          const selected = i === j;
          b.setAttribute(\'aria-selected\', selected ? \'true\' : \'false\');
          tabPanels[j].style.display = selected ? \'\' : \'none\';
        });

        // When switching to a new tab, open its FIRST accordion
        tabPanels.forEach((panel, j) => {
          const triggers = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
          const panelsArr = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
          triggers.forEach((t, k) => {
            t.setAttribute(\'aria-expanded\', i === j && k === 0 ? \'true\' : \'false\');
            panelsArr[k].setAttribute(\'aria-hidden\', i === j && k === 0 ? \'false\' : \'true\');
            panelsArr[k].style.maxHeight = i === j && k === 0 ? (panelsArr[k].scrollHeight + \'px\') : \'0px\';
            if (i === j && k === 0) {
              panelsArr[k].removeAttribute(\'hidden\');
              t.closest(\'.bde-accordion-item\').classList.add(\'open\');
            } else {
              t.closest(\'.bde-accordion-item\').classList.remove(\'open\');
            }
          });
        });
        // Also show the matching image for the first accordion item in the new tab
        tabPanels.forEach((panel, j) => {
          const images = Array.from(panel.querySelectorAll(\'.bde-accordion-image\'));
          images.forEach((img, k) => {
            const shouldShow = i === j && k === 0;
            img.classList.toggle(\'active\', shouldShow);
            img.style.display = shouldShow ? \'\' : \'none\';
          });
        });
      });
    });

    // Set only the first tabpanel visible by default
    tabPanels.forEach((panel, i) => {
      panel.style.display = i === 0 ? \'\' : \'none\';
    });
    tabButtons.forEach((btn, i) => {
      btn.setAttribute(\'aria-selected\', i === 0 ? \'true\' : \'false\');
    });
  }

  function initDesktopAccordions(tabPanels) {
    const allTriggers = Array.from(module.querySelectorAll(\'.show-desktop .bde-accordion-trigger\'));

    allTriggers.forEach(btn => {
      btn.onclick = null;
      btn.addEventListener(\'click\', function () {
        const visiblePanel = tabPanels.find(panel => panel.style.display !== \'none\');
        const triggers = Array.from(visiblePanel.querySelectorAll(\'.bde-accordion-trigger\'));
        const panels = Array.from(visiblePanel.querySelectorAll(\'.bde-accordion-panel\'));
        const images = Array.from(visiblePanel.querySelectorAll(\'.bde-accordion-image\'));

        triggers.forEach((t, i) => {
          const isClicked = t === btn;
          const shouldOpen = isClicked && t.getAttribute(\'aria-expanded\') !== \'true\';

          // Panel logic
          t.setAttribute(\'aria-expanded\', shouldOpen ? \'true\' : \'false\');
          panels[i].setAttribute(\'aria-hidden\', shouldOpen ? \'false\' : \'true\');
          panels[i].style.maxHeight = shouldOpen ? (panels[i].scrollHeight + \'px\') : \'0px\';

          // Item styling
          const item = t.closest(\'.bde-accordion-item\');
          if (item) {
            item.classList.toggle(\'open\', shouldOpen);
          }

          // Image logic
          if (images[i]) {
            if (shouldOpen) {
              // Hide all other images
              images.forEach((img, j) => {
                img.classList.remove(\'active\');
                img.style.display = \'none\';
              });

              // Show matching image
              images[i].classList.add(\'active\');
              images[i].style.display = \'\';
            } else {
              // Hide if closing the one that was open
              images[i].classList.remove(\'active\');
              images[i].style.display = \'none\';
            }
          }
        });
      });
    });
  }

  function initDesktop() {
    const tabButtons = Array.from(module.querySelectorAll(\'.bde-tab\'));
    const tabPanels = Array.from(module.querySelectorAll(\'.bde-tabpanel\'));

    tabPanels.forEach((panel, i) => {
      panel.style.display = i === 0 ? \'\' : \'none\';

      const triggers = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
      const panelsArr = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
      const imagesArr = Array.from(panel.querySelectorAll(\'.bde-accordion-image\'));

      triggers.forEach((t, k) => {
        const isFirst = i === 0 && k === 0;

        t.setAttribute(\'aria-expanded\', isFirst ? \'true\' : \'false\');
        panelsArr[k].setAttribute(\'aria-hidden\', isFirst ? \'false\' : \'true\');
        panelsArr[k].style.maxHeight = isFirst ? (panelsArr[k].scrollHeight + \'px\') : \'0px\';

        if (imagesArr[k]) {
          if (isFirst) {
            imagesArr[k].classList.add(\'active\');
            imagesArr[k].style.display = \'\';
          } else {
            imagesArr[k].classList.remove(\'active\');
            imagesArr[k].style.display = \'none\';
          }
        }

        const item = t.closest(\'.bde-accordion-item\');
        if (item) {
          item.classList.toggle(\'open\', isFirst);
        }
      });
    });

    tabButtons.forEach((btn, i) => {
      btn.setAttribute(\'aria-selected\', i === 0 ? \'true\' : \'false\');
    });

    initDesktopTabs(tabButtons, tabPanels);
    initDesktopAccordions(tabPanels);

    // Show the first image in the visible panel on load
    const visiblePanel = tabPanels.find(panel => panel.style.display !== \'none\');
    if (visiblePanel) {
      const images = Array.from(visiblePanel.querySelectorAll(\'.bde-accordion-image\'));
      if (images.length > 0) {
        images[0].classList.add(\'active\');
      }
    }
  }

  function initAll() {
    if (isMobile()) {
      requestAnimationFrame(() => {
        const trigger = module.querySelector(\'.bde-mobile-tab-trigger\');
        if (trigger) initMobileTabs();
      });
    } else {
      initDesktop();
    }
  }

  initAll();

  let prevIsMobile = isMobile();
  window.addEventListener(\'resize\', () => {
    const currIsMobile = isMobile();
    if (currIsMobile !== prevIsMobile) {
      prevIsMobile = currIsMobile;
      initAll();
    }
  });
})();'],'scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(\'%%UNIQUESLUG%%\');',
],],

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
