<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Topnavaccordion",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Topnavaccordion extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Top Nav Accordion';
    }

    static function className()
    {
        return 'autogenerated-bce-topnavaccordion';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return ['content' => ['eyebrow' => ['text' => 'Lorem ipsum dolor'], 'heading' => ['text' => 'Lorem ipsum dolor sit amet'], 'subhead' => ['text' => 'Lorem ipsum dolor sit amet consectetur adipiscing elit'], 'content' => ['text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.'], 'buttons' => ['primary_button' => ['text' => 'Contact sales', 'link' => '#'], 'secondary_button' => ['text' => 'Learn more', 'link' => '#']]]];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "navigator",
        "Navigator",
        [c(
        "tabs",
        "Tabs",
        [c(
        "tab_title",
        "Tab Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "accordion",
        "Accordion",
        [c(
        "content_icon",
        "Content Icon",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content_title",
        "Content Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "new_control",
        "New Control",
        [],
        ['type' => 'alert_box', 'layout' => 'vertical', 'alertBoxOptions' => ['style' => 'default', 'content' => '<p>Upload or choose your image or animation (JSON) file.</p>']],
        false,
        false,
        [],
      ), c(
        "media",
        "Media",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "animation_speed",
        "Animation Speed",
        [],
        ['type' => 'number', 'layout' => 'inline', 'items' => [['text' => '0.5x', 'label' => 'Label', 'value' => '0.5'], ['text' => '1x', 'value' => '1'], ['text' => '2x', 'value' => '2']], 'rangeOptions' => ['min' => 0, 'max' => 3, 'step' => 0.1]],
        false,
        false,
        [],
      ), c(
        "loop_animation",
        "Loop Animation",
        [],
        ['type' => 'toggle', 'layout' => 'inline', 'items' => [['text' => 'Yes', 'label' => 'Label', 'value' => 'Yes'], ['text' => 'No', 'value' => 'No']]],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Tab', 'buttonName' => 'Add Tab']],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['inlineScripts' => [';(function(){
  const config = {
    slidesPerView: 1,
    spaceBetween: 20,
    observer: true,
    observeParents: true,
    observeSlideChildren: true,
    navigation: {
      nextEl: \'.slider-navigation .swiper-button-next-%%UNIQUESLUG%%\',
      prevEl: \'.slider-navigation .swiper-button-prev-%%UNIQUESLUG%%\'
    },
    pagination: {
      el: \'.slider-navigation .swiper-pagination-%%UNIQUESLUG%%\',
      clickable: true,
      type: \'bullets\'
    }
  };

  function initColumnsSlider() {
    document
      .querySelectorAll(\'.swiper-%%UNIQUESLUG%%\')
      .forEach(el => {
        if (!el.swiper) {
          new Swiper(el, config);
        } else {
          el.swiper.update();
        }
      });
  }

  initColumnsSlider();

  window.addEventListener(\'resize\', initColumnsSlider);

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on(\'builder:loaded builder:rendered\', initColumnsSlider);
  }
})();
',';(function () {
  const module = document.querySelector(\'.autogenerated-bce-topnavaccordion\');
  if (!module) return;

  function isMobile() {
    return window.matchMedia(\'(max-width: 1023px)\').matches;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MOBILE: dropdown‑style tabs + per‑panel Swiper instances
  function initMobileTabs() {
    const trigger     = module.querySelector(".bde-mobile-tab-trigger");
    const dropdown    = module.querySelector(".bde-mobile-dropdown-options");
    const tabContents = module.querySelectorAll(".bde-mobile-tab-content");
    if (!trigger || !dropdown || tabContents.length === 0) return;

    const tabTitles = Array.from(tabContents).map(tab => tab.dataset.tabTitle);
    let   activeIndex = 0;

    trigger.addEventListener("click", function () {
      const expanded = this.getAttribute("aria-expanded") === "true";
      this.setAttribute("aria-expanded", !expanded);
      dropdown.style.display = expanded ? "none" : "block";
    });

    function rebuildDropdown(active) {
      dropdown.innerHTML = "";
      tabTitles.forEach((title, i) => {
        if (i === active) return;
        const li = document.createElement("li");
        li.dataset.tabIndex = i;
        li.textContent = title;
        dropdown.appendChild(li);

        li.addEventListener("click", function () {
          activeIndex = i;
          trigger.querySelector(".bde-accordion-title").innerText = this.innerText;
          trigger.setAttribute("aria-expanded", "false");
          dropdown.style.display = "none";

          tabContents.forEach((tab, j) => {
            tab.style.display = j === activeIndex ? "block" : "none";
          });

          const swiperEl = module.querySelector(`.swiper-${activeIndex}`);
          if (swiperEl && !swiperEl.classList.contains("swiper-initialized")) {
            new Swiper(`.swiper-${activeIndex}`, {
              slidesPerView: 1,
              spaceBetween: 24,
              pagination: {
                el: `.swiper-pagination-${activeIndex}`,
                clickable: true
              },
              navigation: {
                nextEl: `.swiper-button-next-${activeIndex}`,
                prevEl: `.swiper-button-prev-${activeIndex}`
              }
            });
          }

          rebuildDropdown(activeIndex);
        });
      });
    }

    // init the very first Swiper (panel 0)
    const firstSwiper = module.querySelector(`.swiper-0`);
    if (firstSwiper && !firstSwiper.classList.contains("swiper-initialized")) {
      new Swiper(`.swiper-0`, {
        slidesPerView: 1,
        spaceBetween: 24,
        pagination: {
          el: `.swiper-pagination-0`,
          clickable: true
        },
        navigation: {
          nextEl: `.swiper-button-next-0`,
          prevEl: `.swiper-button-prev-0`
        }
      });
    }

    rebuildDropdown(activeIndex);
  }

  // ────────────────────────────────────────────────────────────────────────────
  // UTILITY: clear inline hides, then replay a Lottie animation
  function revealAndReplayLottie(wrapper, idx) {
    wrapper.style.cssText = \'\';
    wrapper.style.setProperty(\'display\',    \'block\',   \'important\');
    wrapper.style.setProperty(\'visibility\', \'visible\', \'important\');
    wrapper.classList.remove(\'bd-hidden\',\'hidden\',\'breakdance-hide\');
    if (wrapper._lottieInstance) {
      wrapper._lottieInstance.goToAndPlay(0, true);
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // DESKTOP TABS: show one tab panel and auto-open its first accordion
  function initDesktopTabs(tabButtons, tabPanels) {
    tabButtons.forEach((btn, ti) => {
      btn.addEventListener(\'click\', () => {
        tabButtons.forEach((b, j) => {
          const active = ti === j;
          b.setAttribute(\'aria-selected\', active);
          tabPanels[j].style.display = active ? \'\' : \'none\';
        });
        tabPanels[ti].querySelector(\'.bde-accordion-trigger\')?.click();
      });
    });
  }

  // ────────────────────────────────────────────────────────────────────────────
  // DESKTOP ACCORDIONS: clear then set .open, .active, and Lottie
  function initDesktopAccordions(tabPanels) {
    // bind all triggers once
    module.querySelectorAll(\'.bde-accordion-trigger\').forEach(btn => {
      btn.addEventListener(\'click\', () => {
        // 1) find the visible tab-panel
        const panel = tabPanels.find(p => p.style.display !== \'none\');

        // 2) collect the lists in that panel
        const triggers    = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
        const panelsArr   = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
        const images      = Array.from(panel.querySelectorAll(\'.bde-accordion-image\'));
        const lotties     = Array.from(panel.querySelectorAll(\'.bde-lottie-animation\'));

        // 3) figure out which index was clicked
        const idx = triggers.indexOf(btn);

        // 4) Reset everything: ARIA, heights, .open, .active, hide Lotties
        triggers.forEach((t, i) => {
          const isOpen = i === idx;
          t.setAttribute(\'aria-expanded\', isOpen);
          panelsArr[i].setAttribute(\'aria-hidden\', !isOpen);
          panelsArr[i].style.maxHeight = isOpen
            ? panelsArr[i].scrollHeight + \'px\'
            : \'0\';
          t.closest(\'.bde-accordion-item\')?.classList.toggle(\'open\', isOpen);
        });

        // 5) Images: remove all .active, then add to the clicked one
        images.forEach(img => img.classList.remove(\'active\'));
        if (images[idx]) images[idx].classList.add(\'active\');

        // 6) Lotties: hide all, then replay the clicked one
        lotties.forEach((l, i) => {
          if (i === idx) {
            revealAndReplayLottie(l, i);
          } else {
            l.style.display = \'none\';
          }
        });
      });
    });
  }


  // ────────────────────────────────────────────────────────────────────────────
  // MASTER DESKTOP INIT: defaults + wire handlers
  function initDesktop() {
    const tabButtons = Array.from(module.querySelectorAll(\'.bde-tab\'));
    const tabPanels  = Array.from(module.querySelectorAll(\'.bde-tabpanel\'));

    // default state: show only first panel, open its accordion #0
    tabPanels.forEach((panel, pi) => {
      panel.style.display = (pi === 0) ? \'\' : \'none\';

      const triggers = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
      const panels   = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
      const images   = Array.from(panel.querySelectorAll(\'.bde-accordion-image\'));
      const lotties  = Array.from(panel.querySelectorAll(\'.bde-lottie-animation\'));

      triggers.forEach((t, ai) => {
        const firstOpen = (pi === 0 && ai === 0);

        // ARIA + height
        t.setAttribute(\'aria-expanded\', firstOpen);
        panels[ai].setAttribute(\'aria-hidden\', !firstOpen);
        panels[ai].style.maxHeight = firstOpen
          ? panels[ai].scrollHeight + \'px\'
          : \'0\';

        // .open class on the item
        const item = t.closest(\'.bde-accordion-item\');
        if (item) item.classList.toggle(\'open\', firstOpen);

        // clear inline hides & toggle .active on the one image
        images.forEach((img, j) => {
          img.style.removeProperty(\'display\');
          img.style.removeProperty(\'visibility\');
          img.classList.toggle(\'active\', firstOpen && j === ai);
        });

        // Lottie
        if (lotties[ai]) {
          if (firstOpen) revealAndReplayLottie(lotties[ai], ai);
          else           lotties[ai].style.display = \'none\';
        }
      });
    });

    initDesktopTabs(tabButtons, tabPanels);
    initDesktopAccordions(tabPanels);

    //
    // **FALLBACK**: if for any reason the first image still
    // isn’t active, force it here:
    //
    const firstImg = tabPanels[0]?.querySelector(\'.bde-accordion-image\');
    if (firstImg && !firstImg.classList.contains(\'active\')) {
      firstImg.style.removeProperty(\'display\');
      firstImg.style.removeProperty(\'visibility\');
      firstImg.classList.add(\'active\');
    }
  }


  // ────────────────────────────────────────────────────────────────────────────
  // OVERALL INIT (mobile vs desktop)
  function initAll() {
    if (isMobile()) initMobileTabs();
    else            initDesktop();
  }

  initAll();
  let wasMobile = isMobile();
  window.addEventListener(\'resize\', () => {
    const now = isMobile();
    if (now !== wasMobile) {
      wasMobile = now;
      initAll();
    }
  });
})();
'],'scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],'title' => 'Swiper',],'1' =>  ['title' => 'Lottie','scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/lottie-web@5/lottie_light-v-5-7-8.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/lottie-web@5/breakdanceLottie.js'],'inlineScripts' => ['(function watchAndInitLottie() {
  const baseSelector      = "%%SELECTOR%%";
  const wrapperSelector   = `${baseSelector} .bde-lottie-animation`;
  const initializedWrappers = new WeakSet();

  // ─── 1) Core Lottie init (unchanged) ────────────────────────────────────────
  function initLottie(wrapper) {
    if (!wrapper || initializedWrappers.has(wrapper)) return;

    const path  = wrapper.dataset.src;
    const speed = parseFloat(wrapper.dataset.speed || "1");
    const loop  = ["true","1"].includes(wrapper.dataset.loop);

    function tryInit(el) {
      const isVisible = el.offsetParent !== null;
      if (!isVisible || el._lottieInstance) return;

      const anim = window.lottie?.loadAnimation({
        container: el,
        renderer:  "svg",
        loop:      false,
        autoplay:  false,
        path
      });
      if (!anim) return;

      anim.setSpeed(speed);
      el._lottieInstance = anim;

      anim.addEventListener("DOMLoaded", () => {
        el.style.display = "";             // make sure it\'s visible
        anim.goToAndPlay(0, true);
      });

      if (loop) {
        anim.addEventListener("complete", () => {
          if (el.offsetParent !== null) anim.goToAndPlay(0, true);
        });
      }

      initializedWrappers.add(el);
    }

    tryInit(wrapper);

    new MutationObserver(() => tryInit(wrapper))
      .observe(wrapper, { attributes: true, attributeFilter: ["style","class"] });
  }

  // ─── 2) Watch for accordion/tab show/hide to replay ───────────────────────
  function observePanelVisibility(wrapper) {
    const panel = wrapper.closest(".bde-tabpanel, .bde-accordion-panel");
    if (!panel) return;

    new MutationObserver(() => {
      const isVisible = panel.offsetParent !== null || panel.style.display !== "none";

      if (isVisible && wrapper.style.display === "none") {
        wrapper.style.display = "";
      }
      if (isVisible && wrapper._lottieInstance) {
        wrapper._lottieInstance.goToAndPlay(0, true);
      }
    })
    .observe(panel, { attributes: true, attributeFilter: ["style","class","aria-hidden"] });
  }

  // ─── 3) “Normal” initAll for everything _except_ first tabpanel ────────────
  function initAllExceptFirst() {
    document.querySelectorAll(wrapperSelector).forEach(wrapper => {
      const tab = wrapper.closest(".bde-tabpanel");
      if (tab?.id === "tabpanel-1") return;   // skip the very first panel
      initLottie(wrapper);
      observePanelVisibility(wrapper);
    });
  }

  // ─── 4) On DOM load + mutations, run that init ─────────────────────────────
  const rootObserver = new MutationObserver(initAllExceptFirst);
  rootObserver.observe(document.body, { childList: true, subtree: true });
  initAllExceptFirst();

  // ─── 5) Now “late‐load” #tabpanel‑1 when it scrolls into view ────────────
  const firstPanel = document.querySelector("#tabpanel-1");
  if (firstPanel) {
    const io = new IntersectionObserver((entries, obs) => {
      if (entries[0].isIntersecting) {
        firstPanel
          .querySelectorAll(wrapperSelector)
          .forEach(wrapper => {
            initLottie(wrapper);
            observePanelVisibility(wrapper);
          });
        obs.disconnect();
      }
    }, { threshold: 0.25 });
    io.observe(firstPanel);
  }

  // ─── 6) Keep your “accordion & tab click → re‑run initAllExceptFirst” ────
  document
    .querySelectorAll(\'.bde-accordion-item, .bde-tab\')
    .forEach(el => el.addEventListener(\'click\', () => {
      setTimeout(initAllExceptFirst, 100);
    }));
})();
'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],['script' => 'window.BreakdanceLottie("%%SELECTOR%%", {{ item.media|json_encode }})',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(\'%%UNIQUESLUG%%\');',
],['script' => '(function universalLottieInit() {

  const baseSelector = "%%SELECTOR%%";
  const wrapperSelector = `${baseSelector} .bde-lottie-animation`;
  let initialized = false;

  function init() {
    if (initialized) return;

    const wrapper = document.querySelector(wrapperSelector);
    if (!wrapper || !wrapper.offsetParent) return;

    // Check for misplaced SVG
    const rogue = wrapper.parentElement?.querySelector("svg, canvas");
    const nested = wrapper.querySelector("svg, canvas");

    if (rogue && !nested) {
      wrapper.appendChild(rogue);
      console.log("🛠️ Moved rogue animation into wrapper");
    }

    // If nothing rendered yet, force manual Lottie load
    if (!wrapper.querySelector("svg, canvas")) {
      wrapper.innerHTML = "";

      const anim = window.lottie?.loadAnimation({
        container: wrapper,
        renderer: "{{ content.lottie.renderer ?? \'svg\' }}"
        path: "{{ content.lottie.asset_url }}"
      });

      if (anim) {
        anim.addEventListener("DOMLoaded", () => {
          anim.loop = true;
          anim.play();
        });

        anim.addEventListener("complete", () => {
          anim.goToAndPlay(0, true); // Manual fallback loop
        });
      }
    }

    initialized = true;
  }

  // Run once immediately
  init();

  // Watch for editor hydration and DOM changes
  const root = document.querySelector(baseSelector);
  if (!root) return;

  const observer = new MutationObserver(() => init());
  observer.observe(root, { childList: true, subtree: true });

  // Auto disconnect after 3s
  setTimeout(() => observer.disconnect(), 3000);
})();
',
],],

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],['script' => '(function watchAndInitLottie() {
  const baseSelector = "%%SELECTOR%%";
  const wrapperSelector = `${baseSelector} .bde-lottie-animation`;

  function initLottie(wrapper) {
    if (!wrapper || wrapper.dataset.initialized === "true") return;

    const path = wrapper.dataset.src;
    const renderer = wrapper.dataset.renderer || "svg";
    const loop = ["true", "1"].includes(wrapper.dataset.loop);
    const autoplay = ["true", "1"].includes(wrapper.dataset.autoplay);
    const speed = parseFloat(wrapper.dataset.speed || "1");
    const trigger = wrapper.dataset.trigger || "accordion";

    console.log("⏳ Initializing Lottie:", { path, loop, autoplay, speed, trigger });

    const anim = window.lottie?.loadAnimation({
      container: wrapper,
      renderer,
      loop,
      autoplay: false, // We control play manually
      path
    });

    if (!anim) {
      return;
    }

    anim.setSpeed(speed);
    wrapper.dataset.initialized = "true";
    wrapper._lottieInstance = anim;

    const panel = wrapper.closest(".bde-tabpanel");

    // Log initial visibility of the panel
    if (panel) {
      const isVisible = panel.offsetParent !== null;
    }

    // When Lottie is ready, attempt to play if visible
    anim.addEventListener("DOMLoaded", () => {

      setTimeout(() => {
        const shouldPlay =
          trigger === "accordion" &&
          autoplay &&
          panel &&
          panel.offsetParent !== null;

        if (shouldPlay) {
          anim.goToAndPlay(0, true);
        } else {
        }
      }, 100);
    });

    anim.addEventListener("complete", () => {
      console.log("🔁 Animation complete:", path);
      if (loop) {
        anim.goToAndPlay(0, true);
      }
    });

    // Watch accordion visibility for dynamic play
    if (trigger === "accordion" && autoplay && panel) {
      const observer = new MutationObserver(() => {
        const isNowVisible = panel.offsetParent !== null;
        if (isNowVisible) {
          anim.goToAndPlay(0, true);
        }
      });
      observer.observe(panel, {
        attributes: true,
        attributeFilter: ["class", "style"]
      });
    }
  }

  function initAll() {
    const wrappers = document.querySelectorAll(wrapperSelector);
    wrappers.forEach(initLottie);
  }

  console.log("🧪 Running watchAndInitLottie inline script");
  
  const observer = new MutationObserver(() => initAll());
  observer.observe(document.body, { childList: true, subtree: true });

  initAll();
})();
',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
