<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;
use function OpkeyCustomElements\getSharedDefaults;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Topnavaccordion",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Topnavaccordion extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Top Nav Accordion';
    }

    static function className()
    {
        return 'autogenerated-bce-topnavaccordion';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => getSharedDefaults(),
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "navigator",
        "Navigator",
        [c(
        "tabs",
        "Tabs",
        [c(
        "tab_title",
        "Tab Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "tab_image_",
        "Tab Image  ",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "accordion",
        "Accordion",
        [c(
        "content_icon",
        "Content Icon",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content_title",
        "Content Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Untitled Tab', 'buttonName' => 'Add Tab']],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['inlineScripts' => [';(function(){
  const config = {
    slidesPerView: 1,
    spaceBetween: 20,
    observer: true,
    observeParents: true,
    observeSlideChildren: true,
    navigation: {
      nextEl: \'.slider-navigation .swiper-button-next-%%UNIQUESLUG%%\',
      prevEl: \'.slider-navigation .swiper-button-prev-%%UNIQUESLUG%%\'
    },
    pagination: {
      el: \'.slider-navigation .swiper-pagination-%%UNIQUESLUG%%\',
      clickable: true,
      type: \'bullets\'
    }
  };

  function initColumnsSlider() {
    document
      .querySelectorAll(\'.swiper-%%UNIQUESLUG%%\')
      .forEach(el => {
        if (!el.swiper) {
          new Swiper(el, config);
        } else {
          el.swiper.update();
        }
      });
  }

  initColumnsSlider();

  window.addEventListener(\'resize\', initColumnsSlider);

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on(\'builder:loaded builder:rendered\', initColumnsSlider);
  }
})();
',';(function() {
  const module = document.querySelector(\'.autogenerated-bce-topnavaccordion\');
  if (!module) return;

  function isMobile() {
    return window.matchMedia(\'(max-width: 1023px)\').matches;
  }

  // ---- MOBILE LOGIC ----

  let mobilePanelsOpen = false; // Track state so Swiper stays in sync

  function getMobileTabPairs() {
    const pairs = [];
    const tabTriggers = module.querySelectorAll(\'.show-mobile .bde-mobile-tab-trigger\');
    tabTriggers.forEach(trigger => {
      const panel = trigger.nextElementSibling;
      if (panel && panel.classList.contains(\'bde-accordion-panel\')) {
        pairs.push({trigger, panel});
      }
    });
    return pairs;
  }

  function closePanel(pair) {
    pair.panel.style.display = \'none\';
    pair.panel.setAttribute(\'aria-hidden\', \'true\');
    pair.trigger.setAttribute(\'aria-expanded\', \'false\');
    const item = pair.trigger.closest(\'.bde-accordion-item\');
    if (item) item.classList.remove(\'open\');
  }

  function openPanel(pair) {
    pair.panel.style.display = \'\';
    pair.panel.setAttribute(\'aria-hidden\', \'false\');
    pair.trigger.setAttribute(\'aria-expanded\', \'true\');
    const item = pair.trigger.closest(\'.bde-accordion-item\');
    if (item) item.classList.add(\'open\');
  }

  function setAllMobilePanels(open, tabPairs) {
    tabPairs.forEach(pair => {
      open ? openPanel(pair) : closePanel(pair);
    });
    mobilePanelsOpen = open;
  }

  function initMobileTabs() {
    const tabPairs = getMobileTabPairs();
    setAllMobilePanels(false, tabPairs); // Hide all on load

    // Remove previous click handlers to avoid stacking
    tabPairs.forEach(pair => pair.trigger.onclick = null);

    // All panels open/close in sync
    tabPairs.forEach((pair) => {
      pair.trigger.onclick = function() {
        setAllMobilePanels(!mobilePanelsOpen, tabPairs);
      };
    });

    // Swiper slide change: keep all in sync
    const swiperEl = document.querySelector(\'.swiper-%%UNIQUESLUG%%\');
    if (swiperEl && swiperEl.swiper) {
      swiperEl.swiper.on(\'slideChange\', function () {
        setAllMobilePanels(mobilePanelsOpen, tabPairs);
      });
    }
  }

  // ---- DESKTOP LOGIC ----

  function getVisiblePanelAccordions(tabPanels) {
    const activePanel = tabPanels.find(panel => panel.style.display !== \'none\');
    if (!activePanel) return { triggers: [], panels: [] };
    const triggers = Array.from(activePanel.querySelectorAll(\'.bde-accordion-trigger\'));
    const panels = Array.from(activePanel.querySelectorAll(\'.bde-accordion-panel\'));
    return { triggers, panels };
  }

  function initDesktopTabs(tabButtons, tabPanels) {
    tabButtons.forEach((btn, i) => {
      btn.addEventListener(\'click\', function() {
        tabButtons.forEach((b, j) => {
          const selected = i === j;
          b.setAttribute(\'aria-selected\', selected ? \'true\' : \'false\');
          tabPanels[j].style.display = selected ? \'\' : \'none\';
        });

        // When switching to a new tab, open its FIRST accordion
        tabPanels.forEach((panel, j) => {
          const triggers = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
          const panelsArr = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
          triggers.forEach((t, k) => {
            t.setAttribute(\'aria-expanded\', i === j && k === 0 ? \'true\' : \'false\');
            panelsArr[k].setAttribute(\'aria-hidden\', i === j && k === 0 ? \'false\' : \'true\');
            panelsArr[k].style.maxHeight = i === j && k === 0 ? (panelsArr[k].scrollHeight + \'px\') : \'0px\';
            if (i === j && k === 0) {
              panelsArr[k].removeAttribute(\'hidden\');
              t.closest(\'.bde-accordion-item\').classList.add(\'open\');
            } else {
              t.closest(\'.bde-accordion-item\').classList.remove(\'open\');
            }
          });
        });
      });
    });

    // Set only the first tabpanel visible by default
    tabPanels.forEach((panel, i) => {
      panel.style.display = i === 0 ? \'\' : \'none\';
    });
    tabButtons.forEach((btn, i) => {
      btn.setAttribute(\'aria-selected\', i === 0 ? \'true\' : \'false\');
    });
  }

  function initDesktopAccordions(tabPanels) {
    // Toggle accordions within the visible tab panel
    const allTriggers = Array.from(module.querySelectorAll(\'.show-desktop .bde-accordion-trigger\'));
    allTriggers.forEach(btn => {
      btn.onclick = null; // Remove previous handlers!
      btn.addEventListener(\'click\', function() {
        const { triggers, panels } = getVisiblePanelAccordions(tabPanels);
        triggers.forEach((t, i) => {
          const isClicked = t === btn;
          const isAlreadyOpen = t.getAttribute(\'aria-expanded\') === \'true\';
          if (isClicked) {
            const open = !isAlreadyOpen;
            t.setAttribute(\'aria-expanded\', open ? \'true\' : \'false\');
            panels[i].setAttribute(\'aria-hidden\', open ? \'false\' : \'true\');
            panels[i].style.maxHeight = open ? (panels[i].scrollHeight + \'px\') : \'0px\';
            if (open) {
              panels[i].removeAttribute(\'hidden\');
              t.closest(\'.bde-accordion-item\').classList.add(\'open\');
            } else {
              t.closest(\'.bde-accordion-item\').classList.remove(\'open\');
            }
          } else {
            t.setAttribute(\'aria-expanded\', \'false\');
            panels[i].setAttribute(\'aria-hidden\', \'true\');
            panels[i].style.maxHeight = \'0px\';
            t.closest(\'.bde-accordion-item\').classList.remove(\'open\');
          }
        });
      });
    });
  }

  function initDesktop() {
    const tabButtons = Array.from(module.querySelectorAll(\'.bde-tab\'));
    const tabPanels = Array.from(module.querySelectorAll(\'.bde-tabpanel\'));

    // Only show first tab and first accordion open
    tabPanels.forEach((panel, i) => {
      panel.style.display = i === 0 ? \'\' : \'none\';
      const triggers = Array.from(panel.querySelectorAll(\'.bde-accordion-trigger\'));
      const panelsArr = Array.from(panel.querySelectorAll(\'.bde-accordion-panel\'));
      triggers.forEach((t, k) => {
        t.setAttribute(\'aria-expanded\', i === 0 && k === 0 ? \'true\' : \'false\');
        panelsArr[k].setAttribute(\'aria-hidden\', i === 0 && k === 0 ? \'false\' : \'true\');
        panelsArr[k].style.maxHeight = i === 0 && k === 0 ? (panelsArr[k].scrollHeight + \'px\') : \'0px\';
        if (i === 0 && k === 0) {
          panelsArr[k].removeAttribute(\'hidden\');
          t.closest(\'.bde-accordion-item\').classList.add(\'open\');
        } else {
          t.closest(\'.bde-accordion-item\').classList.remove(\'open\');
        }
      });
    });
    tabButtons.forEach((btn, i) => {
      btn.setAttribute(\'aria-selected\', i === 0 ? \'true\' : \'false\');
    });

    initDesktopTabs(tabButtons, tabPanels);
    initDesktopAccordions(tabPanels);
  }

  // ---- INIT SWITCHER ----

  function initAll() {
    if (isMobile()) {
      initMobileTabs();
    } else {
      initDesktop();
    }
  }

  // --- On load
  initAll();

  // --- On resize, re-init if switching between mobile/desktop
  let prevIsMobile = isMobile();
  window.addEventListener(\'resize\', () => {
    const currIsMobile = isMobile();
    if (currIsMobile !== prevIsMobile) {
      prevIsMobile = currIsMobile;
      initAll();
    }
  });
})();
'],'scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(\'%%UNIQUESLUG%%\');',
],],

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
