<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Logoslider",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Logoslider extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Logo Slider';
    }

    static function className()
    {
        return 'autogenerated-bce-logoslider';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => [
                'eyebrow' => ['text' => 'Lorem ipsum dolor'],
                'heading' => ['text' => 'Lorem ipsum dolor sit amet'],
                'subhead' => ['text' => 'Lorem ipsum dolor sit amet consectetur adipiscing elit'],
                'content' => ['text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.'],
                'buttons' => [
                    'primary_button' => ['text' => 'Contact sales', 'link' => '#'],
                    'secondary_button' => ['text' => 'Learn more', 'link' => '#']
                ],
            ],
            'design' => [
                'style' => [
                    'variant' => 'style1',
                ],
                'slider' => [
                    'settings' => [
                        'speed' => ['number' => 525, 'unit' => 's', 'style' => '525s'],
                        'autoplay' => 'enabled',
                    ],
                ],
            ],
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "style",
        "Style",
        [c(
        "variant",
        "Variant",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'style1', 'text' => 'Style 1'], ['value' => 'style2', 'text' => 'Style 2']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "layout",
        "Layout",
        [c(
        "width",
        "Width",
        [],
        ['type' => 'dropdown', 'layout' => 'vertical', 'items' => [['value' => 'full_width', 'text' => 'Full width'], ['value' => 'container', 'text' => 'Container']]],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "slider",
        "Slider",
        [c(
        "settings",
        "Settings",
        [c(
        "speed",
        "Speed",
        [],
        ['type' => 'unit', 'layout' => 'inline', 'unitOptions' => ['types' => ['s'], 'defaultType' => 's'], 'rangeOptions' => ['min' => 10, 'max' => 600, 'step' => 10]],
        false,
        false,
        [],
      ), c(
        "autoplay",
        "Autoplay",
        [],
        ['type' => 'dropdown', 'layout' => 'inline', 'items' => [['value' => 'disabled', 'text' => 'Disabled'], ['value' => 'enabled', 'text' => 'Enabled']]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical', 'sectionOptions' => ['type' => 'popout']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple'], ['text' => 'Transparent', 'value' => 'transparent']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ),
      c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical', 'condition' => [[['path' => 'design.style.variant', 'operand' => 'equals', 'value' => 'style1']]]],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical', 'condition' => [[['path' => 'design.style.variant', 'operand' => 'equals', 'value' => 'style1']]]],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical', 'condition' => [[['path' => 'design.style.variant', 'operand' => 'equals', 'value' => 'style1']]]],
        false,
        false,
        [],
      ), c(
        "buttons",
        "Buttons",
        [getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Primary Button",
      "primary_button",
       ['condition' => [[['path' => 'content.buttons.remove_', 'operand' => 'is not set', 'value' => '']]], 'type' => 'popout']
     ), getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Secondary Button",
      "secondary_button",
       ['condition' => [[['path' => 'content.buttons.remove_', 'operand' => 'is not set', 'value' => '']]], 'type' => 'popout']
     )],
        ['type' => 'section', 'layout' => 'vertical', 'condition' => [[['path' => 'design.style.variant', 'operand' => 'equals', 'value' => 'style1']]]],
        false,
        false,
        [],
      ), c(
        "logos",
        "Logos",
        [c(
        "logo",
        "Logo",
        [c(
        "image",
        "Image",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical', 'mediaOptions' => ['multiple' => false]],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => 'Logo Item', 'defaultTitle' => 'Logo Item', 'buttonName' => 'Add Logo', 'galleryMode' => true, 'galleryMediaPath' => 'image']],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['inlineScripts' => ['function updateLogoBarMarquee() {
  document.querySelectorAll(\'.un-logo-bar__marquee-content.carousel-type__marquee\').forEach(function(el) {
    var durationSec = parseFloat(el.getAttribute(\'data-marquee-duration\')) || 525;
    el.style.setProperty(\'--marquee-duration\', durationSec + \'s\');
  });
}
window.addEventListener(\'DOMContentLoaded\', updateLogoBarMarquee);
window.addEventListener(\'resize\', updateLogoBarMarquee);
setTimeout(updateLogoBarMarquee, 100);
'],'title' => 'Slider Adjustments',],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return false;
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return [['name' => 'un-image-carousel-container', 'template' => '{% if design.list.type == \'animated\' %} 
	yes
{% endif %}']];
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url']];
    }

    static function additionalClasses()
    {
        return [
            ['name' => 'layout--full-width', 'template' => '{{ design.layout.width == \'full_width\' or not design.layout.width }}'],
            ['name' => 'layout--container', 'template' => '{{ design.layout.width == \'container\' }}'],
            ['name' => 'logoslider--style1', 'template' => '{{ design.style.variant == \'style1\' or not design.style.variant }}'],
            ['name' => 'logoslider--style2', 'template' => '{{ design.style.variant == \'style2\' }}'],
            ['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'],
            ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'],
            ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}'],
            ['name' => 'theme--transparent', 'template' => '{{ design.theme_color.color == \'transparent\' }}'],
        ];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
