<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;

\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Usecasescustomscroll",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Usecasescustomscroll extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Usecases + Custom Scroll';
    }

    static function className()
    {
        return 'autogenerated-bce-usecasescustomscroll';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => [
                'slides' => [
                    [
                        'eyebrow' => 'Use Case',
                        'title' => 'Certify every update without the fire drill.',
                        'description' => '<p>Oracle and Workday push regular platform updates. Validate the entire landscape and reduce production risk with confidence.</p>',
                        'cta_label' => 'Read Case Study',
                        'cta_text' => 'See how global teams certify updates with confidence.',
                        'tags' => [
                            ['label' => 'Impact Analysis'],
                            ['label' => 'Testing'],
                            ['label' => 'Configuration']
                        ],
                        'right_image_alt' => ''
                    ],
                    [
                        'eyebrow' => 'Use Case',
                        'title' => 'Roll out new geographies or business units faster.',
                        'description' => '<p>Clone, configure, test, and train from one platform. Standardize go-lives and reduce manual overhead.</p>',
                        'cta_label' => 'Explore Workflow',
                        'cta_text' => 'Get the rollout playbook for multi-entity transformation.',
                        'tags' => [
                            ['label' => 'Discovery'],
                            ['label' => 'Design'],
                            ['label' => 'Training']
                        ],
                        'right_image_alt' => ''
                    ]
                ]
            ]
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "slides",
        "Slides",
        [c(
        "eyebrow",
        "Eyebrow",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "title",
        "Title",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      ), c(
        "description",
        "Description",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "cta_label",
        "CTA Label",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "cta_text",
        "CTA Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "tags",
        "Tags",
        [c(
        "label",
        "Label",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{label}', 'defaultTitle' => 'Tag', 'buttonName' => 'Add Tag']],
        false,
        false,
        [],
      ), c(
        "right_image",
        "Right Side Image",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "right_image_alt",
        "Right Side Image Alt Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'placeholder' => 'Describe the image for accessibility'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Slide', 'buttonName' => 'Add Slide']],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return false;
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return false;
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [
            ['accepts' => 'string', 'path' => 'content.slides.title'],
            ['accepts' => 'string', 'path' => 'content.slides.description'],
            ['accepts' => 'string', 'path' => 'content.slides.cta_label'],
            ['accepts' => 'string', 'path' => 'content.slides.cta_text'],
            ['accepts' => 'string', 'path' => 'content.slides.tags.label'],
            ['accepts' => 'string', 'path' => 'content.slides.right_image_alt']
        ];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return false;
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
