<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Leftnavtwocolumnright",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Leftnavtwocolumnright extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Left Nav + Resources';
    }

    static function className()
    {
        return 'autogenerated-bce-leftnavtwocolumnright';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return ['content' => ['eyebrow' => ['text' => 'Lorem ipsum dolor'], 'heading' => ['text' => 'Lorem ipsum dolor sit amet'], 'subhead' => ['text' => 'Lorem ipsum dolor sit amet consectetur adipiscing elit'], 'content' => ['text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.'], 'categories' => ['simple_list_' => false, 'category' => [['title' => 'Category 1', 'resources' => [['icon' => ['url' => '/wp-content/uploads/2025/06/icon-robot.svg'], 'heading' => 'RESOURCE TYPE', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', 'button' => ['text' => 'Learn more', 'url' => '#']], ['icon' => ['url' => '/wp-content/uploads/2025/06/icon-robot.svg'], 'heading' => 'RESOURCE TYPE', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', 'button' => ['text' => 'Learn more', 'url' => '#']]]], ['title' => 'Category 2', 'resources' => [['icon' => ['url' => '/wp-content/uploads/2025/06/icon-robot.svg'], 'heading' => 'RESOURCE TYPE', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', 'button' => ['text' => 'Learn more', 'url' => '#']]]]]]]];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['value' => 'purple', 'text' => 'Purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "categories",
        "Categories",
        [c(
        "simple_list_",
        "Simple list?",
        [],
        ['type' => 'toggle', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "category",
        "Category",
        [c(
        "title",
        "Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "resources",
        "Resources",
        [c(
        "icon",
        "Icon",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Button",
      "button",
       ['type' => 'popout']
     )],
        ['type' => 'repeater', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],'inlineScripts' => [';(function () {
  const config = {
    slidesPerView: 1,
    slidesPerGroup: 1,
    spaceBetween: 20,
    grid: { rows: 1, fill: "row" },
    breakpoints: {
      600: {
        slidesPerView: 2,
        slidesPerGroup: 2,
        grid: { rows: 2, fill: "row" }
      },
      1024: {
        slidesPerView: 2,
        slidesPerGroup: 4,
        grid: { rows: 2, fill: "row" }
      }
    },
    navigation: {
      nextEl: ".slider-navigation .swiper-button-next-%%UNIQUESLUG%%",
      prevEl: ".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"
    },
    pagination: {
      el: ".slider-navigation .swiper-pagination-%%UNIQUESLUG%%",
      clickable: true,
      type: "bullets"
    }
  };

  function equalizeCardHeights(wrapper) {
    const cards = wrapper.querySelectorAll(\'.swiper-slide .card\');
    let maxHeight = 0;

    // Reset heights first
    cards.forEach(card => {
      card.style.height = \'auto\';
    });

    // Find max height
    cards.forEach(card => {
      maxHeight = Math.max(maxHeight, card.offsetHeight);
    });

    // Apply uniform height
    cards.forEach(card => {
      card.style.height = `${maxHeight}px`;
    });
  }

  function initColumnsSlider() {
    document.querySelectorAll(".swiper-%%UNIQUESLUG%%").forEach((el) => {
      const container = el.closest(".module-container");
      const paginationEl = container.querySelector(".slider-navigation .swiper-pagination-%%UNIQUESLUG%%");
      config.pagination.el = paginationEl;

      if (!el.swiper) {
        const swiper = new Swiper(el, config);
        wireCategoryFilter(swiper, el);
      }
    });
  }

  function wireCategoryFilter(swiper, sliderEl) {
    const container = sliderEl.closest(".module-container");
    const tabs = container.querySelectorAll(".bde-tab[data-category-index]");
    const dropdown = container.querySelector("#category-select-%%UNIQUESLUG%%");
    const wrapper = sliderEl.querySelector(".swiper-wrapper");
    const allSlides = container.querySelectorAll(".all-slide-groups .swiper-slide");

    function showCategory(catIndex) {
      catIndex = String(catIndex).trim();
      wrapper.innerHTML = "";

      let slideCount = 0;

      allSlides.forEach((slide) => {
        if (String(slide.dataset.categoryIndex).trim() === catIndex) {
          wrapper.appendChild(slide.cloneNode(true));
          slideCount++;
        }
      });

      swiper.slides = swiper.wrapperEl.querySelectorAll(`.${swiper.params.slideClass}`);
      swiper.update();

      setTimeout(() => {
        if (swiper.pagination?.el) {
          swiper.pagination.render();
          swiper.pagination.update();
        }
      }, 50);

      swiper.slideTo(0, 0);

      tabs.forEach((t) => {
        const isActive = String(t.dataset.categoryIndex).trim() === catIndex;
        t.setAttribute("aria-selected", isActive ? "true" : "false");
        t.classList.toggle("is-active", isActive);
      });

      // ====== Show/hide nav based on resource count ======
      const sliderNav = container.querySelector(\'.slider-navigation-%%UNIQUESLUG%%\');
      if (sliderNav) {
        if (slideCount > 4) {
          sliderNav.style.display = \'\';
          sliderNav.querySelectorAll(\'button\').forEach(btn => btn.disabled = false);
        } else {
          sliderNav.style.display = \'none\';
          sliderNav.querySelectorAll(\'button\').forEach(btn => btn.disabled = true);
        }
      }
    }

    tabs.forEach((tab) => {
      tab.addEventListener("click", () => {
        showCategory(tab.dataset.categoryIndex);
      });
    });

    if (dropdown) {
      dropdown.addEventListener("change", (e) => {
        showCategory(e.target.value);
      });
    }

    if (tabs.length > 0) {
      showCategory(tabs[0].dataset.categoryIndex);
    }
  }

  initColumnsSlider();

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on("builder:loaded builder:rendered", initColumnsSlider);
  }
})();
'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(\'%%UNIQUESLUG%%\');',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.columns.box.button.text'], ['accepts' => 'string', 'path' => 'content.columns.box.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url'], ['accepts' => 'string', 'path' => 'content.categories.category[4].resources.content.text'], ['accepts' => 'string', 'path' => 'content.categories.category[4].resources.content.link.url'], ['accepts' => 'string', 'path' => 'content.categories.category[3].resources.button.text'], ['accepts' => 'string', 'path' => 'content.categories.category[3].resources.button.link.url']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}'], ['name' => 'simple-list', 'template' => '{{ content.categories.simple_list_ ? \'yes\' : \'\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
