<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;


\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Applicationlogos",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Applicationlogos extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Application Logos';
    }

    static function className()
    {
        return 'autogenerated-bce-applicationlogos';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return false;
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['value' => 'purple', 'text' => 'Purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "eyebrow",
        "Eyebrow",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "heading",
        "Heading",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "subhead",
        "Subhead",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'text', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "content",
        "Content",
        [c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "support_copy",
        "Support Copy",
        [],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "buttons",
        "Buttons",
        [c(
        "remove_",
        "Remove?",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Primary Button",
      "primary_button",
       ['condition' => [[['path' => 'content.buttons.remove_', 'operand' => 'is not set', 'value' => '']]], 'type' => 'popout']
     ), getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Secondary Button",
      "secondary_button",
       ['condition' => [[['path' => 'content.buttons.remove_', 'operand' => 'is not set', 'value' => '']]], 'type' => 'popout']
     )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "logos",
        "Logos",
        [c(
        "logos",
        "Logos",
        [c(
        "image",
        "Image",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical', 'mediaOptions' => ['multiple' => false]],
        false,
        false,
        [],
      ), c(
        "size",
        "Size",
        [],
        ['type' => 'media_size_dropdown', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "link",
        "Link",
        [],
        ['type' => 'link', 'layout' => 'vertical'],
        false,
        false,
        [],
      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => 'Logo Item', 'defaultTitle' => 'Logo Item', 'buttonName' => 'Add Logo', 'galleryMode' => true, 'galleryMediaPath' => 'image']],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],'inlineScripts' => [';(function(){
  const config = {
    slidesPerView: 1,
    slidesPerGroup: 1,
    spaceBetween: 20,
    grid: { rows: 1, fill: \'row\' },

    breakpoints: {
      // Small screens: single column
      600:  { 
        slidesPerView: 2, 
        slidesPerGroup: 2, 
        grid: { rows: 2, fill: \'row\' } // 2x2 grid (2 per col, 2 rows)
      },
      // Desktop: 2x2 grid (shows 4 cards at once)
      1024: { 
        slidesPerView: 2, 
        slidesPerGroup: 4, 
        grid: { rows: 2, fill: \'row\' } 
      }
    },

    navigation: {
      nextEl: \'.slider-navigation .swiper-button-next-%%UNIQUESLUG%%\',
      prevEl: \'.slider-navigation .swiper-button-prev-%%UNIQUESLUG%%\'
    },
    pagination: {
      el: \'.slider-navigation .swiper-pagination-%%UNIQUESLUG%%\',
      clickable: true,
      type: \'bullets\'
    }
  };

  function initColumnsSlider() {
    document
      .querySelectorAll(\'.swiper-%%UNIQUESLUG%%\')
      .forEach(el => {
        if (!el.swiper) {
          new Swiper(el, config);
        }
      });
  }

  initColumnsSlider();

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on(\'builder:loaded builder:rendered\', initColumnsSlider);
  }
})();
'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%UNIQUESLUG%%\',
  selector: \'.swiper-%%UNIQUESLUG%%\',
  settings: {"slidesPerView":1,"spaceBetween":32,"grid":{"rows":1,"fill":"row"},"breakpoints":{"600":{"slidesPerView":3,"slidesPerGroup":3,"grid":{"rows":1}},"1024":{"slidesPerView":4,"slidesPerGroup":4,"grid":{"rows":2,"fill":"row"}}},"navigation":{"nextEl":".slider-navigation .swiper-button-next-%%UNIQUESLUG%%","prevEl":".slider-navigation .swiper-button-prev-%%UNIQUESLUG%%"}},
  paginationSettings: {"el":".slider-navigation .swiper-pagination-%%UNIQUESLUG%%","clickable":true,"type":"bullets"}
});',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(\'%%UNIQUESLUG%%\');',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.content.text'], ['accepts' => 'string', 'path' => 'content.content.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.text'], ['accepts' => 'string', 'path' => 'content.buttons.add_button.button.link.url'], ['accepts' => 'string', 'path' => 'content.columns.box.button.text'], ['accepts' => 'string', 'path' => 'content.columns.box.button.link.url'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.text'], ['accepts' => 'string', 'path' => 'content.buttons.secondary_button.link.url']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.buttons.add_button.button.custom.size.full_width_at', 'content.buttons.add_button.button.styles', 'content.buttons.button.custom.size.full_width_at', 'content.buttons.button.styles', 'content.buttons.secondary_button.styles.size.full_width_at', 'content.buttons.secondary_button.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
