<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;

\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Emailbarbutton",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Emailbarbutton extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Email Bar + Button';
    }

    static function className()
    {
        return 'autogenerated-bce-emailbarbutton';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => [
                'shortcode' => [
                    'full_shortcode' => '',
                ],
                'button' => [
                    'button' => [
                        'text' => 'Get demo',
                        'link' => '#',
                    ],
                ],
            ],
            'design' => [
                'styles' => [
                    'style' => 'style-1',
                ],
            ],
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [
            c(
                "styles",
                "Style",
                [
                    c(
                        "style",
                        "Style",
                        [],
                        [
                            'type' => 'button_bar',
                            'layout' => 'vertical',
                            'items' => [
                                ['value' => 'style-1', 'text' => 'Style 1'],
                                ['value' => 'style-2', 'text' => 'Style 2'],
                            ],
                            'buttonBarOptions' => ['size' => 'small', 'layout' => 'default'],
                        ],
                        false,
                        false,
                        []
                    ),
                ],
                ['type' => 'section'],
                false,
                false,
                []
            ),
            c(
                "theme_color",
                "Theme Color",
                [
                    c(
                        "color",
                        "Color",
                        [],
                        [
                        'type' => 'button_bar',
                        'layout' => 'vertical',
                        'items' => [
                            ['value' => 'white', 'text' => 'White'],
                            ['value' => 'light-gray', 'text' => 'Light Gray'],
                            ['value' => 'purple', 'text' => 'Purple'],
                        ],
                        'buttonBarOptions' => ['size' => 'small', 'layout' => 'default'],
                        ],
                        false,
                        false,
                        []
                    ),
                ],
                ['type' => 'section'],
                false,
                false,
                []
            ),
            c(
                "remove_padding",
                "Remove Padding",
                [
                    c(
                        "remove_top",
                        "Remove Top",
                        [],
                        ['type' => 'toggle', 'layout' => 'inline'],
                        false,
                        false,
                        []
                    ),
                    c(
                        "remove_bottom",
                        "Remove Bottom",
                        [],
                        ['type' => 'toggle', 'layout' => 'inline'],
                        false,
                        false,
                        []
                    ),
                ],
                ['type' => 'section'],
                false,
                false,
                []
            ),
            c(
                "email_bar",
                "Email Bar",
                [
                    c(
                        "background_color",
                        "Background Color",
                        [],
                        ['type' => 'color', 'layout' => 'vertical'],
                        false,
                        false,
                        []
                    ),
                    c(
                        "width",
                        "Width",
                        [],
                        [
                            'type' => 'unit',
                            'layout' => 'inline',
                            'unitOptions' => [
                                'types' => ['%', 'px'],
                                'defaultType' => '%',
                            ],
                        ],
                        false,
                        false,
                        []
                    ),
                    c(
                        "placeholder_color",
                        "Placeholder Color",
                        [],
                        ['type' => 'color', 'layout' => 'vertical'],
                        false,
                        false,
                        []
                    ),
                    c(
                        "text_color",
                        "Text Color",
                        [],
                        ['type' => 'color', 'layout' => 'vertical'],
                        false,
                        false,
                        []
                    ),
                    c(
                        "border_color",
                        "Border Color",
                        [],
                        ['type' => 'color', 'layout' => 'vertical'],
                        false,
                        false,
                        []
                    ),
                    c(
                        "radius_type",
                        "Radius Type",
                        [],
                        [
                            'type' => 'dropdown',
                            'layout' => 'inline',
                            'items' => [
                                ['value' => 'round', 'text' => 'Round'],
                                ['value' => 'square', 'text' => 'Square'],
                                ['value' => 'custom', 'text' => 'Custom'],
                            ],
                        ],
                        false,
                        false,
                        []
                    ),
                    c(
                        "radius_custom",
                        "Custom Radius",
                        [],
                        [
                            'type' => 'unit',
                            'layout' => 'inline',
                            'unitOptions' => ['types' => ['px'], 'defaultType' => 'px'],
                            'condition' => [
                                'path' => 'design.email_bar.radius_type',
                                'operand' => 'equals',
                                'value' => 'custom',
                            ],
                        ],
                        false,
                        false,
                        []
                    ),
                    c(
                        "padding_x",
                        "Horizontal Padding",
                        [],
                        [
                            'type' => 'unit',
                            'layout' => 'inline',
                            'unitOptions' => ['types' => ['px'], 'defaultType' => 'px'],
                        ],
                        false,
                        false,
                        []
                    ),
                    c(
                        "padding_y",
                        "Vertical Padding",
                        [],
                        [
                            'type' => 'unit',
                            'layout' => 'inline',
                            'unitOptions' => ['types' => ['px'], 'defaultType' => 'px'],
                        ],
                        false,
                        false,
                        []
                    ),
                ],
                ['type' => 'section', 'layout' => 'vertical'],
                false,
                false,
                []
            ),
        ];
    }

    static function contentControls()
    {
        return [
            c(
                "shortcode",
                "Shortcode",
                [
                    c(
                        "full_shortcode",
                        "Full Shortcode",
                        [],
                        [
                            'type' => 'text',
                            'layout' => 'vertical',
                            'placeholder' => '[hubspot shortcode]',
                            'textOptions' => ['multiline' => true],
                        ],
                        false,
                        false,
                        []
                    ),
                ],
                ['type' => 'section', 'layout' => 'vertical'],
                false,
                false,
                []
            ),
            c(
                "button",
                "Button",
                [
                    getPresetSection(
                        "EssentialElements\\AtomV1ButtonContent",
                        "Button",
                        "button",
                        ['type' => 'popout']
                    ),
                ],
                ['type' => 'section', 'layout' => 'vertical'],
                false,
                false,
                []
            ),
        ];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return false;
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return false;
    }

    static function nestingRule()
    {
        return ['type' => 'final'];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function availableIn()
    {
        return ['breakdance'];
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return false;
    }

    static function additionalClasses()
    {
        return [
            [
                'name' => 'theme--white',
                'template' => "{{ design.theme_color.color == 'white' or not design.theme_color.color }}\n",
            ],
            [
                'name' => 'theme--light-gray',
                'template' => "{{ design.theme_color.color == 'light-gray' }}",
            ],
            [
                'name' => 'theme--purple',
                'template' => "{{ design.theme_color.color == 'purple' }}",
            ],
        ];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return [];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}

