<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;

\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Bannercards",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Bannercards extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Banner Cards';
    }

    static function className()
    {
        return 'autogenerated-bce-bannercards';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => [
                'cards' => [
                    [
                        'title' => 'Performance Testing',
                        'media' => '/wp-content/plugins/opkey-elements/assets/Placeholder-1280x500.svg',
                    ],
                    [
                        'title' => 'AI Powered API Testing',
                        'media' => '/wp-content/plugins/opkey-elements/assets/Placeholder-1280x500.svg',
                    ],
                    [
                        'title' => 'Record Replay API Traffic',
                        'media' => '/wp-content/plugins/opkey-elements/assets/Placeholder-1280x500.svg',
                    ],
                    [
                        'title' => 'Coverage Reporting',
                        'media' => '/wp-content/plugins/opkey-elements/assets/Placeholder-1280x500.svg',
                    ],
                ],
            ],
            'design' => [
                'layout' => [
                    'card_height' => 430,
                    'bar_height' => 60,
                    'stack_offset' => 36,
                    'image_delay_ms' => 5000,
                ],
                'remove_padding' => [
                    'remove_top' => false,
                    'remove_bottom' => false,
                ],
            ],
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "layout",
        "Layout",
        [c(
        "card_height",
        "Card Height",
        [],
        ['type' => 'number', 'layout' => 'inline', 'rangeOptions' => ['min' => 220, 'max' => 900, 'step' => 1]],
        false,
        false,
        [],

      ), c(
        "bar_height",
        "Top Bar Height",
        [],
        ['type' => 'number', 'layout' => 'inline', 'rangeOptions' => ['min' => 36, 'max' => 140, 'step' => 1]],
        false,
        false,
        [],

      ), c(
        "stack_offset",
        "Stack Offset",
        [],
        ['type' => 'number', 'layout' => 'inline', 'rangeOptions' => ['min' => 18, 'max' => 120, 'step' => 1]],
        false,
        false,
        [],

      ), c(
        "image_delay_ms",
        "Image Auto Change (ms)",
        [],
        ['type' => 'number', 'layout' => 'inline', 'rangeOptions' => ['min' => 1500, 'max' => 20000, 'step' => 100]],
        false,
        false,
        [],

      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],

      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],

      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],

      )],
        ['type' => 'section'],
        false,
        false,
        [],

      )];
    }

    static function contentControls()
    {
        return [c(
        "cards",
        "Cards",
        [c(
        "title",
        "Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],

      ), c(
        "media",
        "Image or Video",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical', 'mediaOptions' => ['acceptedFileTypes' => ['image', 'video'], 'multiple' => false]],
        false,
        false,
        [],

      )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Card', 'buttonName' => 'Add Card']],
        false,
        false,
        [],

      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' => ['inlineScripts' => ['(function () {
  "use strict";

  function initStack(root) {
    if (!root || root.__bdeBannerCardsInit) return;
    root.__bdeBannerCardsInit = true;

    const cards = Array.from(root.querySelectorAll(".bde-banner-card"));
    if (cards.length < 2) return;

    let order = cards.map((_, i) => i);
    const gap = parseInt(root.dataset.stackOffset || "36", 10) || 36;
    const desktopHorizontalStep = Math.max(10, Math.round(gap * 0.55));
    function getHorizontalStep() {
      return window.matchMedia("(max-width: 767px)").matches ? 0 : desktopHorizontalStep;
    }
    const maxXOffset = (cards.length - 1) * desktopHorizontalStep;
    const imageDelayMs = parseInt(root.dataset.imageDelayMs || "5000", 10) || 5000;
    const videoFallbackMs = 10000;
    let autoTimer = null;

    root.style.setProperty("--bde-stack-right-space", maxXOffset + "px");

    function moveCardToFront(index) {
      order = order.filter(i => i !== index);
      order.push(index);
      render();
      scheduleNext();
    }

    function render() {
      const horizontalStep = window.matchMedia("(max-width: 767px)").matches ? 0 : getHorizontalStep();
      order.forEach((cardIndex, stackIndex) => {
        const card = cards[cardIndex];
        const isFront = stackIndex === order.length - 1;
        const xOffset = (order.length - 1 - stackIndex) * horizontalStep;
        const yOffset = stackIndex * gap;
        card.style.zIndex = String(20 + stackIndex);
        card.style.transform = "translate(" + xOffset + "px," + yOffset + "px)";
        card.classList.toggle("is-front", isFront);
        card.setAttribute("aria-hidden", isFront ? "false" : "true");

        const cardVideo = card.querySelector("video");
        if (cardVideo) {
          if (isFront) {
            const playPromise = cardVideo.play();
            if (playPromise && typeof playPromise.catch === "function") {
              playPromise.catch(function () {});
            }
          } else {
            cardVideo.pause();
            try { cardVideo.currentTime = 0; } catch (e) {}
          }
        }
      });
    }

    function getFrontIndex() {
      return order[order.length - 1];
    }

    function getNextIndex() {
      const frontIndex = getFrontIndex();
      return (frontIndex + 1) % cards.length;
    }

    function getFrontDelayMs() {
      const frontCard = cards[getFrontIndex()];
      if (!frontCard) return imageDelayMs;

      const frontVideo = frontCard.querySelector("video");
      if (!frontVideo) return imageDelayMs;

      const d = Number(frontVideo.duration);
      if (Number.isFinite(d) && d > 0) {
        return Math.max(1500, Math.min(30000, Math.round(d * 1000 + 600)));
      }
      return videoFallbackMs;
    }

    function clearAutoTimer() {
      if (autoTimer) {
        clearTimeout(autoTimer);
        autoTimer = null;
      }
    }

    function scheduleNext() {
      clearAutoTimer();
      const waitMs = getFrontDelayMs();
      autoTimer = setTimeout(function () {
        moveCardToFront(getNextIndex());
      }, waitMs);
    }

    cards.forEach((card, index) => {
      const trigger = card.querySelector(".bde-banner-card-bar");
      if (!trigger) return;

      trigger.addEventListener("click", function () {
        moveCardToFront(index);
      });
    });

    cards.forEach((card) => {
      const video = card.querySelector("video");
      if (!video) return;
      video.addEventListener("loadedmetadata", function () {
        if (card.classList.contains("is-front")) {
          scheduleNext();
        }
      });
    });

    render();
    scheduleNext();

    let resizeRaf = null;
    window.addEventListener("resize", function () {
      if (resizeRaf) cancelAnimationFrame(resizeRaf);
      resizeRaf = requestAnimationFrame(function () {
        render();
      });
    });
  }

  function scan() {
    document.querySelectorAll(".autogenerated-bce-bannercards .bde-banner-cards-stack").forEach(initStack);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scan);
  } else {
    scan();
  }

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on("builder:loaded builder:rendered", scan);
  }
})();']]];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return false;
    }

    static function nestingRule()
    {
        return ['type' => 'final'];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function availableIn()
    {
        return ['breakdance'];
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return false;
    }

    static function additionalClasses()
    {
        return false;
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return false;
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}

