<?php

namespace BreakdanceCustomElements;

use function Breakdance\Elements\c;
use function Breakdance\Elements\PresetSections\getPresetSection;

\Breakdance\ElementStudio\registerElementForEditing(
    "BreakdanceCustomElements\\Quoteslidercenterheadshot",
    \Breakdance\Util\getdirectoryPathRelativeToPluginFolder(__DIR__)
);

class Quoteslidercenterheadshot extends \Breakdance\Elements\Element
{
    static function uiIcon()
    {
        return 'SquareIcon';
    }

    static function tag()
    {
        return 'div';
    }

    static function tagOptions()
    {
        return [];
    }

    static function tagControlPath()
    {
        return false;
    }

    static function name()
    {
        return 'Quote Slider + Center Headshot';
    }

    static function className()
    {
        return 'autogenerated-bce-quoteslidercenterheadshot';
    }

    static function category()
    {
        return 'site';
    }

    static function badge()
    {
        return false;
    }

    static function slug()
    {
        return __CLASS__;
    }

    static function template()
    {
        return file_get_contents(__DIR__ . '/html.twig');
    }

    static function defaultCss()
    {
        return file_get_contents(__DIR__ . '/default.css');
    }

    static function defaultProperties()
    {
        return [
            'content' => [
                'quotes' => [
                    'slides' => [
                        [
                            'title' => '',
                            'text' => '',
                            'name' => '',
                            'role_company' => '',
                            'link_to_case_study' => [
                                'text' => '',
                                'link' => ['url' => '']
                            ]
                        ]
                    ]
                ]
            ]
        ];
    }

    static function defaultChildren()
    {
        return false;
    }

    static function cssTemplate()
    {
        $template = file_get_contents(__DIR__ . '/css.twig');
        return $template;
    }

    static function designControls()
    {
        return [c(
        "theme_color",
        "Theme Color",
        [c(
        "color",
        "Color",
        [],
        ['type' => 'button_bar', 'layout' => 'vertical', 'items' => [['value' => 'white', 'text' => 'White'], ['text' => 'Light Gray', 'value' => 'light-gray'], ['text' => 'Purple', 'value' => 'purple']], 'buttonBarOptions' => ['size' => 'small', 'layout' => 'default']],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      ), c(
        "remove_padding",
        "Remove Padding",
        [c(
        "remove_top",
        "Remove Top",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      ), c(
        "remove_bottom",
        "Remove Bottom",
        [],
        ['type' => 'toggle', 'layout' => 'inline'],
        false,
        false,
        [],
      )],
        ['type' => 'section'],
        false,
        false,
        [],
      )];
    }

    static function contentControls()
    {
        return [c(
        "quotes",
        "Quotes",
        [c(
        "slides",
        "Slides",
        [c(
        "title",
        "Title",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "text",
        "Text",
        [],
        ['type' => 'richtext', 'layout' => 'vertical', 'textOptions' => ['multiline' => true]],
        false,
        false,
        [],
      ), c(
        "headshot",
        "Headshot",
        [],
        ['type' => 'wpmedia', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "name",
        "Name",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), c(
        "role_company",
        "Role / Company",
        [],
        ['type' => 'text', 'layout' => 'vertical'],
        false,
        false,
        [],
      ), getPresetSection(
      "EssentialElements\\AtomV1ButtonContent",
      "Link to Case Study",
      "link_to_case_study",
       ['type' => 'popout']
     )],
        ['type' => 'repeater', 'layout' => 'vertical', 'repeaterOptions' => ['titleTemplate' => '{title}', 'defaultTitle' => 'Slide', 'buttonName' => 'Add Slide', 'defaultNewValue' => ['background' => ['lazy_load' => true]]]],
        false,
        false,
        [],
      )],
        ['type' => 'section', 'layout' => 'vertical'],
        false,
        false,
        [],
      )];
    }

    static function settingsControls()
    {
        return [];
    }

    static function dependencies()
    {
        return ['0' =>  ['scripts' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.js','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/breakdance-swiper/breakdance-swiper.js'],'inlineScripts' => [';(function(){
  function syncNavHeadshot(swiperEl, activeIndex) {
    const nav = swiperEl.closest(\'.module-quote\')?.querySelector(\'.slider-nav-headshot\');
    if (!nav) return;

    const slides = swiperEl.querySelectorAll(\'.swiper-slide\');
    const source = slides[activeIndex]?.querySelector(\'.headshot-source img\');
    if (!source) {
      nav.innerHTML = \'\';
      return;
    }

    const clone = source.cloneNode(true);
    clone.removeAttribute(\'srcset\');
    clone.removeAttribute(\'sizes\');
    clone.loading = \'lazy\';
    nav.innerHTML = \'\';
    nav.appendChild(clone);
  }

  const config = {
    slidesPerView: 1,
    slidesPerGroup: 1,
    spaceBetween: 20,
    autoHeight: true,
    loop: true,
    observer: true,
    observeParents: true,
    autoplay: {
      delay: 5000,
      disableOnInteraction: false,
      pauseOnMouseEnter: true
    },

    navigation: {
      nextEl: \'.slider-navigation .swiper-button-next-%%UNIQUESLUG%%\',
      prevEl: \'.slider-navigation .swiper-button-prev-%%UNIQUESLUG%%\'
    },
    on: {
      init: function(swiper) {
        syncNavHeadshot(swiper.el, swiper.realIndex || 0);
      },
      slideChange: function(swiper) {
        syncNavHeadshot(swiper.el, swiper.realIndex || 0);
      }
    }
  };

  function initColumnsSlider() {
    document
      .querySelectorAll(\'.swiper-%%UNIQUESLUG%%\')
      .forEach(el => {
        if (!el.swiper) {
          new Swiper(el, config);
        } else {
          syncNavHeadshot(el, el.swiper.realIndex || 0);
        }
      });
  }

  initColumnsSlider();

  if (window.BREAKDANCE) {
    window.BREAKDANCE.on(\'builder:loaded builder:rendered\', initColumnsSlider);
  }
})();
'],'styles' => ['%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/swiper-bundle.min.css','%%BREAKDANCE_ELEMENTS_PLUGIN_URL%%dependencies-files/swiper@8/breakdance-swiper-preset-defaults.css'],],];
    }

    static function settings()
    {
        return false;
    }

    static function addPanelRules()
    {
        return false;
    }

    static public function actions()
    {
        return [

'onPropertyChange' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%ID%%\',
  selector:\'%%SELECTOR%%\',
  settings:{{ design.slider.settings|json_encode }},
  paginationSettings:{{ design.slider.pagination|json_encode }},
});',
],],

'onBeforeDeletingElement' => [['script' => 'window.BreakdanceSwiper().destroy(
  \'%%ID%%\'
);',
],],

'onMountedElement' => [['script' => 'window.BreakdanceSwiper().update({
  id: \'%%ID%%\',
  selector:\'%%SELECTOR%%\',
  settings:{{ design.slider.settings|json_encode }},
  paginationSettings:{{ design.slider.pagination|json_encode }},
});',
],],];
    }

    static function nestingRule()
    {
        return ["type" => "final",   ];
    }

    static function spacingBars()
    {
        return false;
    }

    static function attributes()
    {
        return false;
    }

    static function experimental()
    {
        return false;
    }

    static function order()
    {
        return 0;
    }

    static function dynamicPropertyPaths()
    {
        return [['accepts' => 'string', 'path' => 'content.quotes.slides.link_to_case_study.text'], ['accepts' => 'string', 'path' => 'content.quotes.slides.link_to_case_study.link.url'], ['accepts' => 'string', 'path' => 'content.quotes.slides.text']];
    }

    static function additionalClasses()
    {
        return [['name' => 'theme--white', 'template' => '{{ design.theme_color.color == \'white\' or not design.theme_color.color }}
'], ['name' => 'theme--light-gray', 'template' => '{{ design.theme_color.color == \'light-gray\' }}'], ['name' => 'theme--purple', 'template' => '{{ design.theme_color.color == \'purple\' }}']];
    }

    static function projectManagement()
    {
        return false;
    }

    static function propertyPathsToWhitelistInFlatProps()
    {
        return ['content.quotes.slides.link_to_case_study.styles.size.full_width_at', 'content.quotes.slides.link_to_case_study.styles'];
    }

    static function propertyPathsToSsrElementWhenValueChanges()
    {
        return false;
    }
}
